### ISSUE TITLE
Issues with interactions with custom Scanners

### ISSUE THREAD

**Issue by Xe** [tailscale/sqlite#32]
I am working on something involving this database driver that makes use of the sql.Null\* types. When making queries that have a mix of NULL and non-NULL values in a column, only NULL values are returned. Consider this SQLite shell session:

```
sqlite> CREATE TABLE foo ( data TEXT );
sqlite> INSERT INTO foo(data) VALUES ('bar');
sqlite> INSERT INTO foo(data) VALUES (NULL);
```

When I run this in Go and query `SELECT data FROM foo ORDER BY rowid`, I get the following (after scanning it into a slice of sql.NullString):

```go
[]sql.NullString{
  {String: "bar", Valid: true},
  {String: "", Valid: true},
}
```

Which is confusing because the SQLite shell returns the following for the moral equivalent of that datatype:

```
sqlite> SELECT data, data IS NOT NULL AS valid FROM foo ORDER BY rowid;
| data | valid |
|------|-------|
| bar  | 1     |
|      | 0     |
```

Here is a minimal reproduction case:

```go
func TestSQLiteBug(t *testing.T) {
	db := sql.OpenDB(sqlite.Connector(":memory:", func(ctx context.Context, conn driver.ConnPrepareContext) error { return nil }, nil))
	err := db.Ping()
	if err != nil {
		t.Fatal(err)
	}

	_, err = db.Exec("CREATE TABLE foo ( data TEXT )")
	if err != nil {
		t.Fatal(err)
	}

	db.Exec("INSERT INTO foo(data) VALUES ('bar')")
	db.Exec("INSERT INTO foo(data) VALUES (NULL)")

	var result []sql.NullString
	rows, err := db.Query("SELECT data FROM foo ORDER BY rowid")
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()

	for rows.Next() {
		var val sql.NullString
		err := rows.Scan(&val)
		if err != nil {
			t.Fatal(err)
		}
		result = append(result, val)
	}

	if len(result) != 2 {
		t.Fatalf("wanted 2 results, not %d", len(result))
	}

	first := result[0]
	second := result[1]

	t.Logf("first:  %#+v", first)
	t.Logf("second: %#+v", second)

	if !first.Valid {
		t.Error("first is not valid but we wanted it to be")
	}

	if first.String != "bar" {
		t.Errorf("first is not \"bar\", got: %q", first.String)
	}

	if second.Valid {
		t.Error("second is valid but we wanted it to not be")
	}
}
```

This fails with the following message:

```
=== RUN   TestSQLiteBug
    sqlite_date_test.go:101: first:  sql.NullString{String:"bar", Valid:true}
    sqlite_date_test.go:102: second: sql.NullString{String:"", Valid:true}
    sqlite_date_test.go:113: second is valid but we wanted it to not be
--- FAIL: TestSQLiteBug (0.00s)
```

There have been other issues when adding left joins into the mix, but details will be provided in the comments when I am able to get a minimal reproduction.

**Comment by krt-z** [comment]
In cgosqlite.h, ColumnText always returns a string, if the actual value is nil, it just returns "".

I think all the Column(Text|Int|Float|etc) functions need to return pointers.  Something like:
```
func (stmt *Stmt) ColumnText(col int) *string {
	str := (*C.char)(unsafe.Pointer(C.sqlite3_column_text(stmt.stmt, C.int(col))))
	n := C.sqlite3_column_bytes(stmt.stmt, C.int(col))
	if str == nil {
		return nil
	}
	if n == 0 {
		empty := ""
		return &empty
	}
	goStr := C.GoStringN(str, n)
	return &goStr
}
```

And the cases in sqliteh.go need to handle nil:
```
		case sqliteh.SQLITE_TEXT:
			v := r.stmt.stmt.ColumnText(i)
			if v == nil {
				dest[i] = nil
			} else {
				dest[i] = *v
			}
```

This worked for your test case but it looks like there's the same problem in scanAll in queryglue.go.  It actually has a comment about NullInt64 but I don't really see if/how it actually works with nulls at a glance.  I'd have to test more later.
```
			// We have a handful of *sql.NullInt64 objects in
			// our tree, so we implement minimal support for
			// them here.
```

I think this is probably pretty tuned to the tailscale schema at the moment.

**Comment by krt-z** [comment]
I had posted something before that was definitely wrong.  I think the problem is rows.Next() in sqlite.go caches the column types based off the first result, which I don't think is safe to do for nullable columns.

If you change this this line https://github.com/tailscale/sqlite/blob/main/sqlite.go#L694 to `switch r.stmt.stmt.ColumnType(i)` instead of using the cached value, your test passes.

It looks like they don't do the caching in the pool code because of this issue https://github.com/tailscale/sqlite/blob/main/sqlitepool/queryglue.go#L214

I don't know if there's any way to avoid calling ColumnType for every column for every row if you want to handle nulls correctly.
